USE [master]
GO

/****** Object:  Database [DLMS]    Script Date: 12/23/2022 4:39:39 PM ******/
CREATE DATABASE [DLMS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DLMS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\DLMS.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DLMS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\DLMS_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DLMS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DLMS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DLMS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DLMS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DLMS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DLMS] SET ARITHABORT OFF 
GO

ALTER DATABASE [DLMS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DLMS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DLMS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DLMS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DLMS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DLMS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DLMS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DLMS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DLMS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DLMS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DLMS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DLMS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DLMS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DLMS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DLMS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DLMS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DLMS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DLMS] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DLMS] SET  MULTI_USER 
GO

ALTER DATABASE [DLMS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DLMS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DLMS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DLMS] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DLMS] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DLMS] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [DLMS] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DLMS] SET  READ_WRITE 
GO

USE [DLMS]
GO

/****** Object:  Table [dbo].[Scheduler]    Script Date: 12/23/2022 4:39:04 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Scheduler](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ModeOfCommunication] [varchar](50) NULL,
	[COMPort] [varchar](50) NULL,
	[Profile] [text] NULL,
	[Parity] [varchar](max) NULL,
	[Baudrate] [varchar](max) NULL,
	[JobStatus] [varchar](max) NULL,
	[IPAddress] [varchar](max) NULL,
	[Clientid] [varchar](max) NULL,
	[PortNo] [varchar](max) NULL,
 CONSTRAINT [PK_Scheduler] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO




